const LANGUAGES = [
  {
    id: "es",
    name: "Spanisch",
    level: "B1",
    pack: "Alltag",
    speech: "es-ES",
    free: true,
    flag: `<svg width="28" height="28" viewBox="0 0 28 28" aria-hidden="true"><rect width="28" height="9.3" fill="#c60b1e"/><rect y="9.3" width="28" height="9.4" fill="#ffc400"/><rect y="18.7" width="28" height="9.3" fill="#c60b1e"/></svg>`,
  },
  {
    id: "fr",
    name: "Französisch",
    level: "A2",
    pack: "Reisen",
    speech: "fr-FR",
    free: true,
    flag: `<svg width="28" height="28" viewBox="0 0 28 28" aria-hidden="true"><rect width="9.3" height="28" fill="#002395"/><rect x="9.3" width="9.4" height="28" fill="#fff"/><rect x="18.7" width="9.3" height="28" fill="#ed2939"/></svg>`,
  },
  {
    id: "ja",
    name: "Japanisch",
    level: "A1",
    pack: "Begrüßung",
    speech: "ja-JP",
    free: false,
    flag: `<svg width="28" height="28" viewBox="0 0 28 28" aria-hidden="true"><rect width="28" height="28" fill="#fff"/><circle cx="14" cy="14" r="7" fill="#bc002d"/></svg>`,
  },
  {
    id: "it",
    name: "Italienisch",
    level: "A1",
    pack: "Grundwortschatz",
    speech: "it-IT",
    free: false,
    flag: `<svg width="28" height="28" viewBox="0 0 28 28" aria-hidden="true"><rect width="9.3" height="28" fill="#009246"/><rect x="9.3" width="9.4" height="28" fill="#fff"/><rect x="18.7" width="9.3" height="28" fill="#ce2b37"/></svg>`,
  },
  {
    id: "en",
    name: "Englisch",
    level: "B1",
    pack: "Alltag",
    speech: "en-GB",
    free: false,
    flag: `<svg width="28" height="28" viewBox="0 0 28 28" aria-hidden="true"><rect width="28" height="28" fill="#012169"/><path d="M0 0l28 28M28 0L0 28" stroke="#fff" stroke-width="5"/><path d="M0 0l28 28M28 0L0 28" stroke="#c8102e" stroke-width="2"/><path d="M14 0v28M0 14h28" stroke="#fff" stroke-width="9"/><path d="M14 0v28M0 14h28" stroke="#c8102e" stroke-width="5"/></svg>`,
  },
];

const WORDS = {
  es: [
    { id: "es-mariposa", word: "mariposa", phonetic: "/ma.ɾi.ˈpo.sa/", pos: "Substantiv", gender: "feminin", translation: "Schmetterling", example: "La mariposa vuela en el jardín.", exampleDe: "Der Schmetterling fliegt im Garten." },
    { id: "es-ventana", word: "ventana", phonetic: "/ben.ˈta.na/", pos: "Substantiv", gender: "feminin", translation: "Fenster", example: "Abre la ventana, por favor.", exampleDe: "Öffne bitte das Fenster." },
    { id: "es-cocina", word: "cocina", phonetic: "/ko.ˈθi.na/", pos: "Substantiv", gender: "feminin", translation: "Küche", example: "La cocina huele a pan.", exampleDe: "Die Küche riecht nach Brot." },
    { id: "es-zapato", word: "zapato", phonetic: "/θa.ˈpa.to/", pos: "Substantiv", gender: "maskulin", translation: "Schuh", example: "Este zapato es muy cómodo.", exampleDe: "Dieser Schuh ist sehr bequem." },
    { id: "es-amigo", word: "amigo", phonetic: "/a.ˈmi.ɣo/", pos: "Substantiv", gender: "maskulin", translation: "Freund", example: "Mi amigo vive en Madrid.", exampleDe: "Mein Freund wohnt in Madrid." },
    { id: "es-ciudad", word: "ciudad", phonetic: "/θju.ˈðað/", pos: "Substantiv", gender: "feminin", translation: "Stadt", example: "La ciudad es grande y ruidosa.", exampleDe: "Die Stadt ist groß und laut." },
    { id: "es-manzana", word: "manzana", phonetic: "/man.ˈθa.na/", pos: "Substantiv", gender: "feminin", translation: "Apfel", example: "Como una manzana cada mañana.", exampleDe: "Ich esse jeden Morgen einen Apfel." },
    { id: "es-lluvia", word: "lluvia", phonetic: "/ˈʎu.βja/", pos: "Substantiv", gender: "feminin", translation: "Regen", example: "La lluvia cae suave hoy.", exampleDe: "Der Regen fällt heute sanft." },
    { id: "es-calle", word: "calle", phonetic: "/ˈka.ʎe/", pos: "Substantiv", gender: "feminin", translation: "Straße", example: "La calle está llena de gente.", exampleDe: "Die Straße ist voller Leute." },
    { id: "es-mesa", word: "mesa", phonetic: "/ˈme.sa/", pos: "Substantiv", gender: "feminin", translation: "Tisch", example: "Pon los platos en la mesa.", exampleDe: "Stell die Teller auf den Tisch." },
    { id: "es-libro", word: "libro", phonetic: "/ˈli.βɾo/", pos: "Substantiv", gender: "maskulin", translation: "Buch", example: "Este libro es interesante.", exampleDe: "Dieses Buch ist interessant." },
    { id: "es-perro", word: "perro", phonetic: "/ˈpe.ro/", pos: "Substantiv", gender: "maskulin", translation: "Hund", example: "El perro corre en el parque.", exampleDe: "Der Hund läuft im Park." },
  ],
  fr: [
    { id: "fr-billet", word: "billet", phonetic: "/bi.jɛ/", pos: "Substantiv", gender: "maskulin", translation: "Fahrkarte", example: "J'achète un billet pour Paris.", exampleDe: "Ich kaufe eine Fahrkarte nach Paris." },
    { id: "fr-gare", word: "gare", phonetic: "/ɡaʁ/", pos: "Substantiv", gender: "feminin", translation: "Bahnhof", example: "Le train part de la gare.", exampleDe: "Der Zug fährt vom Bahnhof ab." },
    { id: "fr-valise", word: "valise", phonetic: "/va.liz/", pos: "Substantiv", gender: "feminin", translation: "Koffer", example: "Ma valise est trop lourde.", exampleDe: "Mein Koffer ist zu schwer." },
    { id: "fr-hotel", word: "hôtel", phonetic: "/o.tɛl/", pos: "Substantiv", gender: "maskulin", translation: "Hotel", example: "L'hôtel est près de la plage.", exampleDe: "Das Hotel liegt nah am Strand." },
    { id: "fr-plage", word: "plage", phonetic: "/plaʒ/", pos: "Substantiv", gender: "feminin", translation: "Strand", example: "Nous marchons sur la plage.", exampleDe: "Wir gehen am Strand spazieren." },
    { id: "fr-passeport", word: "passeport", phonetic: "/pas.pɔʁ/", pos: "Substantiv", gender: "maskulin", translation: "Reisepass", example: "Où est mon passeport ?", exampleDe: "Wo ist mein Reisepass?" },
    { id: "fr-avion", word: "avion", phonetic: "/a.vjɔ̃/", pos: "Substantiv", gender: "maskulin", translation: "Flugzeug", example: "L'avion décolle à midi.", exampleDe: "Das Flugzeug startet um zwölf." },
    { id: "fr-carte", word: "carte", phonetic: "/kaʁt/", pos: "Substantiv", gender: "feminin", translation: "Karte", example: "As-tu une carte de la ville ?", exampleDe: "Hast du eine Karte der Stadt?" },
    { id: "fr-train", word: "train", phonetic: "/tʁɛ̃/", pos: "Substantiv", gender: "maskulin", translation: "Zug", example: "Le train est en retard.", exampleDe: "Der Zug hat Verspätung." },
    { id: "fr-chambre", word: "chambre", phonetic: "/ʃɑ̃bʁ/", pos: "Substantiv", gender: "feminin", translation: "Zimmer", example: "La chambre a une belle vue.", exampleDe: "Das Zimmer hat eine schöne Aussicht." },
    { id: "fr-taxi", word: "taxi", phonetic: "/tak.si/", pos: "Substantiv", gender: "maskulin", translation: "Taxi", example: "Prenons un taxi à l'aéroport.", exampleDe: "Nehmen wir ein Taxi zum Flughafen." },
    { id: "fr-aeroport", word: "aéroport", phonetic: "/ae.ʁɔ.pɔʁ/", pos: "Substantiv", gender: "maskulin", translation: "Flughafen", example: "Nous arrivons à l'aéroport.", exampleDe: "Wir kommen am Flughafen an." },
  ],
  ja: [
    { id: "ja-konnichiwa", word: "こんにちは", phonetic: "konnichiwa", pos: "Begrüßung", gender: "", translation: "Hallo", example: "こんにちは、お元気ですか。", exampleDe: "Hallo, wie geht's dir?" },
    { id: "ja-arigatou", word: "ありがとう", phonetic: "arigatou", pos: "Ausdruck", gender: "", translation: "Danke", example: "ありがとう、助かりました。", exampleDe: "Danke, das hat geholfen." },
    { id: "ja-sumimasen", word: "すみません", phonetic: "sumimasen", pos: "Ausdruck", gender: "", translation: "Entschuldigung", example: "すみません、道を教えてください。", exampleDe: "Entschuldigung, können Sie den Weg erklären?" },
    { id: "ja-ohayou", word: "おはよう", phonetic: "ohayou", pos: "Begrüßung", gender: "", translation: "Guten Morgen", example: "おはよう、よく眠れた？", exampleDe: "Guten Morgen, gut geschlafen?" },
    { id: "ja-sayounara", word: "さようなら", phonetic: "sayounara", pos: "Abschied", gender: "", translation: "Auf Wiedersehen", example: "さようなら、また会いましょう。", exampleDe: "Auf Wiedersehen, bis bald." },
    { id: "ja-hai", word: "はい", phonetic: "hai", pos: "Ausdruck", gender: "", translation: "Ja", example: "はい、わかりました。", exampleDe: "Ja, verstanden." },
    { id: "ja-iie", word: "いいえ", phonetic: "iie", pos: "Ausdruck", gender: "", translation: "Nein", example: "いいえ、大丈夫です。", exampleDe: "Nein, es ist in Ordnung." },
    { id: "ja-hajimemashite", word: "はじめまして", phonetic: "hajimemashite", pos: "Begrüßung", gender: "", translation: "Freut mich", example: "はじめまして、アンナです。", exampleDe: "Freut mich, ich bin Anna." },
  ],
  it: [
    { id: "it-ciao", word: "ciao", phonetic: "/ˈtʃao/", pos: "Begrüßung", gender: "", translation: "Hallo", example: "Ciao, come stai?", exampleDe: "Hallo, wie geht's?" },
    { id: "it-grazie", word: "grazie", phonetic: "/ˈɡrat.tsje/", pos: "Ausdruck", gender: "", translation: "Danke", example: "Grazie per l'aiuto.", exampleDe: "Danke für die Hilfe." },
    { id: "it-perfavore", word: "per favore", phonetic: "/per faˈvo.re/", pos: "Ausdruck", gender: "", translation: "Bitte", example: "Un caffè, per favore.", exampleDe: "Einen Kaffee, bitte." },
    { id: "it-buongiorno", word: "buongiorno", phonetic: "/bwonˈdʒor.no/", pos: "Begrüßung", gender: "", translation: "Guten Tag", example: "Buongiorno, signora.", exampleDe: "Guten Tag, gnädige Frau." },
    { id: "it-acqua", word: "acqua", phonetic: "/ˈak.kwa/", pos: "Substantiv", gender: "feminin", translation: "Wasser", example: "Vorrei un bicchiere d'acqua.", exampleDe: "Ich hätte gern ein Glas Wasser." },
    { id: "it-pane", word: "pane", phonetic: "/ˈpa.ne/", pos: "Substantiv", gender: "maskulin", translation: "Brot", example: "Il pane è ancora caldo.", exampleDe: "Das Brot ist noch warm." },
    { id: "it-casa", word: "casa", phonetic: "/ˈka.sa/", pos: "Substantiv", gender: "feminin", translation: "Haus", example: "La casa è vicino al mare.", exampleDe: "Das Haus liegt nah am Meer." },
    { id: "it-amico", word: "amico", phonetic: "/aˈmi.ko/", pos: "Substantiv", gender: "maskulin", translation: "Freund", example: "Il mio amico parla italiano.", exampleDe: "Mein Freund spricht Italienisch." },
  ],
  en: [
    { id: "en-butterfly", word: "butterfly", phonetic: "/ˈbʌtəflaɪ/", pos: "Substantiv", gender: "", translation: "Schmetterling", example: "The butterfly lands on a flower.", exampleDe: "Der Schmetterling landet auf einer Blume." },
    { id: "en-window", word: "window", phonetic: "/ˈwɪndəʊ/", pos: "Substantiv", gender: "", translation: "Fenster", example: "Please close the window.", exampleDe: "Bitte schließ das Fenster." },
    { id: "en-kitchen", word: "kitchen", phonetic: "/ˈkɪtʃɪn/", pos: "Substantiv", gender: "", translation: "Küche", example: "Dinner is ready in the kitchen.", exampleDe: "Das Abendessen ist in der Küche fertig." },
    { id: "en-friend", word: "friend", phonetic: "/frend/", pos: "Substantiv", gender: "", translation: "Freund", example: "She is my best friend.", exampleDe: "Sie ist meine beste Freundin." },
    { id: "en-city", word: "city", phonetic: "/ˈsɪti/", pos: "Substantiv", gender: "", translation: "Stadt", example: "The city never sleeps.", exampleDe: "Die Stadt schläft nie." },
    { id: "en-rain", word: "rain", phonetic: "/reɪn/", pos: "Substantiv", gender: "", translation: "Regen", example: "The rain stopped at noon.", exampleDe: "Der Regen hörte mittags auf." },
    { id: "en-street", word: "street", phonetic: "/striːt/", pos: "Substantiv", gender: "", translation: "Straße", example: "This street is very quiet.", exampleDe: "Diese Straße ist sehr ruhig." },
    { id: "en-book", word: "book", phonetic: "/bʊk/", pos: "Substantiv", gender: "", translation: "Buch", example: "I borrowed a book from the library.", exampleDe: "Ich habe ein Buch aus der Bibliothek ausgeliehen." },
  ],
};
