package app.wordflow.trainer

object VocabSeed {
    fun all(): List<WordEntity> = es() + fr() + ja() + it() + en()

    private fun w(
        lang: String,
        slug: String,
        word: String,
        translation: String,
        phonetic: String,
        pos: String,
        gender: String,
        example: String,
        exampleDe: String,
    ) = WordEntity(
        id = "$lang-$slug",
        lang = lang,
        word = word,
        translation = translation,
        phonetic = phonetic,
        pos = pos,
        gender = gender,
        example = example,
        exampleDe = exampleDe,
        source = "seed",
    )

    private fun es() = listOf(
        w("es", "agua", "agua", "Wasser", "/ˈa.ɣwa/", "Substantiv", "feminin", "El agua está fría.", "Das Wasser ist kalt."),
        w("es", "pan", "pan", "Brot", "/pan/", "Substantiv", "maskulin", "Compro pan cada mañana.", "Ich kaufe jeden Morgen Brot."),
        w("es", "casa", "casa", "Haus", "/ˈka.sa/", "Substantiv", "feminin", "Mi casa está cerca del parque.", "Mein Haus liegt nah am Park."),
        w("es", "tiempo", "tiempo", "Zeit / Wetter", "/ˈtjem.po/", "Substantiv", "maskulin", "No tengo tiempo hoy.", "Ich habe heute keine Zeit."),
        w("es", "persona", "persona", "Person", "/peɾ.ˈso.na/", "Substantiv", "feminin", "Hay mucha gente en la plaza.", "Auf dem Platz sind viele Leute."),
        w("es", "dia", "día", "Tag", "/ˈdi.a/", "Substantiv", "maskulin", "Hoy es un buen día.", "Heute ist ein guter Tag."),
        w("es", "ano", "año", "Jahr", "/ˈa.ɲo/", "Substantiv", "maskulin", "Este año viajamos a España.", "Dieses Jahr reisen wir nach Spanien."),
        w("es", "mujer", "mujer", "Frau", "/mu.ˈxeɾ/", "Substantiv", "feminin", "La mujer lee un libro.", "Die Frau liest ein Buch."),
        w("es", "hombre", "hombre", "Mann", "/ˈom.bɾe/", "Substantiv", "maskulin", "El hombre espera el autobús.", "Der Mann wartet auf den Bus."),
        w("es", "nino", "niño", "Kind", "/ˈni.ɲo/", "Substantiv", "maskulin", "El niño juega en el jardín.", "Das Kind spielt im Garten."),
        w("es", "trabajo", "trabajo", "Arbeit", "/tɾa.ˈβa.xo/", "Substantiv", "maskulin", "Me gusta mi trabajo.", "Ich mag meine Arbeit."),
        w("es", "escuela", "escuela", "Schule", "/es.ˈkwe.la/", "Substantiv", "feminin", "Los niños van a la escuela.", "Die Kinder gehen zur Schule."),
        w("es", "ciudad", "ciudad", "Stadt", "/θju.ˈðað/", "Substantiv", "feminin", "Madrid es una ciudad grande.", "Madrid ist eine große Stadt."),
        w("es", "comida", "comida", "Essen", "/ko.ˈmi.ða/", "Substantiv", "feminin", "La comida está lista.", "Das Essen ist fertig."),
        w("es", "amigo", "amigo", "Freund", "/a.ˈmi.ɣo/", "Substantiv", "maskulin", "Mi amigo vive en Valencia.", "Mein Freund wohnt in Valencia."),
        w("es", "familia", "familia", "Familie", "/fa.ˈmi.lja/", "Substantiv", "feminin", "Ceno con mi familia.", "Ich esse mit meiner Familie zu Abend."),
        w("es", "mano", "mano", "Hand", "/ˈma.no/", "Substantiv", "feminin", "Dame la mano, por favor.", "Gib mir bitte die Hand."),
        w("es", "ojo", "ojo", "Auge", "/ˈo.xo/", "Substantiv", "maskulin", "Cierra los ojos.", "Schließ die Augen."),
        w("es", "cabeza", "cabeza", "Kopf", "/ka.ˈβe.θa/", "Substantiv", "feminin", "Me duele la cabeza.", "Mir tut der Kopf weh."),
        w("es", "puerta", "puerta", "Tür", "/ˈpweɾ.ta/", "Substantiv", "feminin", "Cierra la puerta.", "Schließ die Tür."),
        w("es", "ventana", "ventana", "Fenster", "/ben.ˈta.na/", "Substantiv", "feminin", "Abre la ventana.", "Öffne das Fenster."),
        w("es", "mesa", "mesa", "Tisch", "/ˈme.sa/", "Substantiv", "feminin", "Pon los platos en la mesa.", "Stell die Teller auf den Tisch."),
        w("es", "silla", "silla", "Stuhl", "/ˈsi.ʎa/", "Substantiv", "feminin", "Siéntate en la silla.", "Setz dich auf den Stuhl."),
        w("es", "libro", "libro", "Buch", "/ˈli.βɾo/", "Substantiv", "maskulin", "Este libro es interesante.", "Dieses Buch ist interessant."),
        w("es", "perro", "perro", "Hund", "/ˈpe.ro/", "Substantiv", "maskulin", "El perro corre en el parque.", "Der Hund läuft im Park."),
        w("es", "gato", "gato", "Katze", "/ˈɡa.to/", "Substantiv", "maskulin", "El gato duerme en el sofá.", "Die Katze schläft auf dem Sofa."),
        w("es", "sol", "sol", "Sonne", "/sol/", "Substantiv", "maskulin", "El sol brilla hoy.", "Die Sonne scheint heute."),
        w("es", "luna", "luna", "Mond", "/ˈlu.na/", "Substantiv", "feminin", "La luna está llena.", "Der Mond ist voll."),
        w("es", "mar", "mar", "Meer", "/maɾ/", "Substantiv", "maskulin", "Nadamos en el mar.", "Wir schwimmen im Meer."),
        w("es", "calle", "calle", "Straße", "/ˈka.ʎe/", "Substantiv", "feminin", "La calle está llena de gente.", "Die Straße ist voller Leute."),
        w("es", "coche", "coche", "Auto", "/ˈko.tʃe/", "Substantiv", "maskulin", "El coche está aparcado.", "Das Auto ist geparkt."),
        w("es", "tren", "tren", "Zug", "/tɾen/", "Substantiv", "maskulin", "El tren sale a las ocho.", "Der Zug fährt um acht ab."),
        w("es", "dinero", "dinero", "Geld", "/di.ˈne.ɾo/", "Substantiv", "maskulin", "No llevo mucho dinero.", "Ich habe nicht viel Geld dabei."),
        w("es", "pregunta", "pregunta", "Frage", "/pɾe.ˈɣun.ta/", "Substantiv", "feminin", "Tengo una pregunta.", "Ich habe eine Frage."),
        w("es", "respuesta", "respuesta", "Antwort", "/res.ˈpwes.ta/", "Substantiv", "feminin", "Su respuesta es clara.", "Seine Antwort ist klar."),
        w("es", "noche", "noche", "Nacht", "/ˈno.tʃe/", "Substantiv", "feminin", "Buenas noches.", "Gute Nacht."),
        w("es", "manzana", "manzana", "Apfel", "/man.ˈθa.na/", "Substantiv", "feminin", "Como una manzana.", "Ich esse einen Apfel."),
        w("es", "leche", "leche", "Milch", "/ˈle.tʃe/", "Substantiv", "feminin", "Quiero un vaso de leche.", "Ich möchte ein Glas Milch."),
        w("es", "gracias", "gracias", "Danke", "/ˈɡɾa.θjas/", "Ausdruck", "", "Muchas gracias por tu ayuda.", "Vielen Dank für deine Hilfe."),
        w("es", "porfavor", "por favor", "Bitte", "/poɾ fa.ˈβoɾ/", "Ausdruck", "", "Un café, por favor.", "Einen Kaffee, bitte."),
    )

    private fun fr() = listOf(
        w("fr", "eau", "eau", "Wasser", "/o/", "Substantiv", "feminin", "L'eau est froide.", "Das Wasser ist kalt."),
        w("fr", "pain", "pain", "Brot", "/pɛ̃/", "Substantiv", "maskulin", "J'achète du pain.", "Ich kaufe Brot."),
        w("fr", "maison", "maison", "Haus", "/mɛ.zɔ̃/", "Substantiv", "feminin", "Notre maison est petite.", "Unser Haus ist klein."),
        w("fr", "temps", "temps", "Zeit / Wetter", "/tɑ̃/", "Substantiv", "maskulin", "Je n'ai pas le temps.", "Ich habe keine Zeit."),
        w("fr", "jour", "jour", "Tag", "/ʒuʁ/", "Substantiv", "maskulin", "Bonne journée !", "Einen schönen Tag!"),
        w("fr", "annee", "année", "Jahr", "/a.ne/", "Substantiv", "feminin", "Cette année je voyage.", "Dieses Jahr reise ich."),
        w("fr", "femme", "femme", "Frau", "/fam/", "Substantiv", "feminin", "La femme lit le journal.", "Die Frau liest die Zeitung."),
        w("fr", "homme", "homme", "Mann", "/ɔm/", "Substantiv", "maskulin", "L'homme attend le bus.", "Der Mann wartet auf den Bus."),
        w("fr", "enfant", "enfant", "Kind", "/ɑ̃.fɑ̃/", "Substantiv", "maskulin", "L'enfant joue dehors.", "Das Kind spielt draußen."),
        w("fr", "travail", "travail", "Arbeit", "/tʁa.vaj/", "Substantiv", "maskulin", "J'aime mon travail.", "Ich mag meine Arbeit."),
        w("fr", "ecole", "école", "Schule", "/e.kɔl/", "Substantiv", "feminin", "Les enfants vont à l'école.", "Die Kinder gehen zur Schule."),
        w("fr", "ville", "ville", "Stadt", "/vil/", "Substantiv", "feminin", "Paris est une belle ville.", "Paris ist eine schöne Stadt."),
        w("fr", "ami", "ami", "Freund", "/a.mi/", "Substantiv", "maskulin", "Mon ami habite à Lyon.", "Mein Freund wohnt in Lyon."),
        w("fr", "famille", "famille", "Familie", "/fa.mij/", "Substantiv", "feminin", "Je dîne avec ma famille.", "Ich esse mit meiner Familie zu Abend."),
        w("fr", "gare", "gare", "Bahnhof", "/ɡaʁ/", "Substantiv", "feminin", "Le train part de la gare.", "Der Zug fährt vom Bahnhof ab."),
        w("fr", "billet", "billet", "Fahrkarte", "/bi.jɛ/", "Substantiv", "maskulin", "J'achète un billet pour Lyon.", "Ich kaufe eine Fahrkarte nach Lyon."),
        w("fr", "valise", "valise", "Koffer", "/va.liz/", "Substantiv", "feminin", "Ma valise est trop lourde.", "Mein Koffer ist zu schwer."),
        w("fr", "hotel", "hôtel", "Hotel", "/o.tɛl/", "Substantiv", "maskulin", "L'hôtel est près de la plage.", "Das Hotel liegt nah am Strand."),
        w("fr", "plage", "plage", "Strand", "/plaʒ/", "Substantiv", "feminin", "Nous marchons sur la plage.", "Wir gehen am Strand spazieren."),
        w("fr", "avion", "avion", "Flugzeug", "/a.vjɔ̃/", "Substantiv", "maskulin", "L'avion décolle à midi.", "Das Flugzeug startet um zwölf."),
        w("fr", "train", "train", "Zug", "/tʁɛ̃/", "Substantiv", "maskulin", "Le train est en retard.", "Der Zug hat Verspätung."),
        w("fr", "merci", "merci", "Danke", "/mɛʁ.si/", "Ausdruck", "", "Merci pour ton aide.", "Danke für deine Hilfe."),
        w("fr", "silvousplait", "s'il vous plaît", "Bitte", "/sil vu plɛ/", "Ausdruck", "", "Un café, s'il vous plaît.", "Einen Kaffee, bitte."),
        w("fr", "bonjour", "bonjour", "Guten Tag", "/bɔ̃.ʒuʁ/", "Begrüßung", "", "Bonjour, comment allez-vous ?", "Guten Tag, wie geht es Ihnen?"),
        w("fr", "livre", "livre", "Buch", "/livʁ/", "Substantiv", "maskulin", "Ce livre est passionnant.", "Dieses Buch ist spannend."),
        w("fr", "chien", "chien", "Hund", "/ʃjɛ̃/", "Substantiv", "maskulin", "Le chien court dans le parc.", "Der Hund läuft im Park."),
        w("fr", "chat", "chat", "Katze", "/ʃa/", "Substantiv", "maskulin", "Le chat dort sur le canapé.", "Die Katze schläft auf dem Sofa."),
        w("fr", "soleil", "soleil", "Sonne", "/sɔ.lɛj/", "Substantiv", "maskulin", "Le soleil brille.", "Die Sonne scheint."),
        w("fr", "lune", "lune", "Mond", "/lyn/", "Substantiv", "feminin", "La lune est pleine.", "Der Mond ist voll."),
        w("fr", "mer", "mer", "Meer", "/mɛʁ/", "Substantiv", "feminin", "Nous nageons dans la mer.", "Wir schwimmen im Meer."),
        w("fr", "rue", "rue", "Straße", "/ʁy/", "Substantiv", "feminin", "Cette rue est calme.", "Diese Straße ist ruhig."),
        w("fr", "voiture", "voiture", "Auto", "/vwa.tyʁ/", "Substantiv", "feminin", "La voiture est garée.", "Das Auto ist geparkt."),
        w("fr", "argent", "argent", "Geld", "/aʁ.ʒɑ̃/", "Substantiv", "maskulin", "Je n'ai pas d'argent.", "Ich habe kein Geld."),
        w("fr", "question", "question", "Frage", "/kɛs.tjɔ̃/", "Substantiv", "feminin", "J'ai une question.", "Ich habe eine Frage."),
        w("fr", "nuit", "nuit", "Nacht", "/nɥi/", "Substantiv", "feminin", "Bonne nuit.", "Gute Nacht."),
        w("fr", "pomme", "pomme", "Apfel", "/pɔm/", "Substantiv", "feminin", "Je mange une pomme.", "Ich esse einen Apfel."),
        w("fr", "lait", "lait", "Milch", "/lɛ/", "Substantiv", "maskulin", "Un verre de lait, s'il te plaît.", "Ein Glas Milch, bitte."),
        w("fr", "porte", "porte", "Tür", "/pɔʁt/", "Substantiv", "feminin", "Ferme la porte.", "Schließ die Tür."),
        w("fr", "fenetre", "fenêtre", "Fenster", "/fə.nɛtʁ/", "Substantiv", "feminin", "Ouvre la fenêtre.", "Öffne das Fenster."),
        w("fr", "table", "table", "Tisch", "/tabl/", "Substantiv", "feminin", "Mets les assiettes sur la table.", "Stell die Teller auf den Tisch."),
    )

    private fun ja() = listOf(
        w("ja", "konnichiwa", "こんにちは", "Hallo / Guten Tag", "konnichiwa", "Begrüßung", "", "こんにちは、お元気ですか。", "Hallo, wie geht's dir?"),
        w("ja", "ohayou", "おはよう", "Guten Morgen", "ohayou", "Begrüßung", "", "おはよう、よく眠れた？", "Guten Morgen, gut geschlafen?"),
        w("ja", "konbanwa", "こんばんは", "Guten Abend", "konbanwa", "Begrüßung", "", "こんばんは。", "Guten Abend."),
        w("ja", "arigatou", "ありがとう", "Danke", "arigatou", "Ausdruck", "", "ありがとう、助かりました。", "Danke, das hat geholfen."),
        w("ja", "sumimasen", "すみません", "Entschuldigung", "sumimasen", "Ausdruck", "", "すみません、道を教えてください。", "Entschuldigung, können Sie den Weg erklären?"),
        w("ja", "hai", "はい", "Ja", "hai", "Ausdruck", "", "はい、わかりました。", "Ja, verstanden."),
        w("ja", "iie", "いいえ", "Nein", "iie", "Ausdruck", "", "いいえ、大丈夫です。", "Nein, es ist in Ordnung."),
        w("ja", "hajimemashite", "はじめまして", "Freut mich", "hajimemashite", "Begrüßung", "", "はじめまして、アンナです。", "Freut mich, ich bin Anna."),
        w("ja", "sayounara", "さようなら", "Auf Wiedersehen", "sayounara", "Abschied", "", "さようなら、また会いましょう。", "Auf Wiedersehen, bis bald."),
        w("ja", "mizu", "水", "Wasser", "mizu", "Substantiv", "", "水をください。", "Wasser bitte."),
        w("ja", "pan", "パン", "Brot", "pan", "Substantiv", "", "パンを食べます。", "Ich esse Brot."),
        w("ja", "ie", "家", "Haus", "ie", "Substantiv", "", "これは私の家です。", "Das ist mein Haus."),
        w("ja", "gakkou", "学校", "Schule", "gakkou", "Substantiv", "", "学校へ行きます。", "Ich gehe zur Schule."),
        w("ja", "tomodachi", "友達", "Freund", "tomodachi", "Substantiv", "", "彼は私の友達です。", "Er ist mein Freund."),
        w("ja", "neko", "猫", "Katze", "neko", "Substantiv", "", "猫が好きです。", "Ich mag Katzen."),
        w("ja", "inu", "犬", "Hund", "inu", "Substantiv", "", "犬が走っています。", "Der Hund läuft."),
        w("ja", "hon", "本", "Buch", "hon", "Substantiv", "", "この本は面白いです。", "Dieses Buch ist interessant."),
        w("ja", "eki", "駅", "Bahnhof", "eki", "Substantiv", "", "駅はどこですか。", "Wo ist der Bahnhof?"),
        w("ja", "densha", "電車", "Zug", "densha", "Substantiv", "", "電車が来ます。", "Der Zug kommt."),
        w("ja", "taberu", "食べる", "essen", "taberu", "Verb", "", "ごはんを食べます。", "Ich esse Reis/Essen."),
        w("ja", "nomu", "飲む", "trinken", "nomu", "Verb", "", "水を飲みます。", "Ich trinke Wasser."),
        w("ja", "iku", "行く", "gehen", "iku", "Verb", "", "東京へ行きます。", "Ich gehe nach Tokio."),
        w("ja", "kuru", "来る", "kommen", "kuru", "Verb", "", "明日来ます。", "Ich komme morgen."),
        w("ja", "ohisashiburi", "お久しぶり", "Lange nicht gesehen", "ohisashiburi", "Ausdruck", "", "お久しぶりです。", "Lange nicht gesehen."),
    )

    private fun it() = listOf(
        w("it", "acqua", "acqua", "Wasser", "/ˈak.kwa/", "Substantiv", "feminin", "Vorrei un bicchiere d'acqua.", "Ich hätte gern ein Glas Wasser."),
        w("it", "pane", "pane", "Brot", "/ˈpa.ne/", "Substantiv", "maskulin", "Il pane è ancora caldo.", "Das Brot ist noch warm."),
        w("it", "casa", "casa", "Haus", "/ˈka.sa/", "Substantiv", "feminin", "La casa è vicino al mare.", "Das Haus liegt nah am Meer."),
        w("it", "tempo", "tempo", "Zeit / Wetter", "/ˈtɛm.po/", "Substantiv", "maskulin", "Non ho tempo oggi.", "Ich habe heute keine Zeit."),
        w("it", "giorno", "giorno", "Tag", "/ˈdʒor.no/", "Substantiv", "maskulin", "Buongiorno!", "Guten Tag!"),
        w("it", "donna", "donna", "Frau", "/ˈdɔn.na/", "Substantiv", "feminin", "La donna legge un libro.", "Die Frau liest ein Buch."),
        w("it", "uomo", "uomo", "Mann", "/ˈwɔ.mo/", "Substantiv", "maskulin", "L'uomo aspetta l'autobus.", "Der Mann wartet auf den Bus."),
        w("it", "bambino", "bambino", "Kind", "/bamˈbi.no/", "Substantiv", "maskulin", "Il bambino gioca nel parco.", "Das Kind spielt im Park."),
        w("it", "lavoro", "lavoro", "Arbeit", "/laˈvo.ro/", "Substantiv", "maskulin", "Mi piace il mio lavoro.", "Ich mag meine Arbeit."),
        w("it", "scuola", "scuola", "Schule", "/ˈskwɔ.la/", "Substantiv", "feminin", "I bambini vanno a scuola.", "Die Kinder gehen zur Schule."),
        w("it", "citta", "città", "Stadt", "/tʃitˈta/", "Substantiv", "feminin", "Roma è una città antica.", "Rom ist eine alte Stadt."),
        w("it", "amico", "amico", "Freund", "/aˈmi.ko/", "Substantiv", "maskulin", "Il mio amico parla italiano.", "Mein Freund spricht Italienisch."),
        w("it", "famiglia", "famiglia", "Familie", "/faˈmiʎ.ʎa/", "Substantiv", "feminin", "Ceno con la mia famiglia.", "Ich esse mit meiner Familie zu Abend."),
        w("it", "ciao", "ciao", "Hallo / Tschüss", "/ˈtʃao/", "Begrüßung", "", "Ciao, come stai?", "Hallo, wie geht's?"),
        w("it", "grazie", "grazie", "Danke", "/ˈɡrat.tsje/", "Ausdruck", "", "Grazie per l'aiuto.", "Danke für die Hilfe."),
        w("it", "perfavore", "per favore", "Bitte", "/per faˈvo.re/", "Ausdruck", "", "Un caffè, per favore.", "Einen Kaffee, bitte."),
        w("it", "buongiorno", "buongiorno", "Guten Tag", "/bwonˈdʒor.no/", "Begrüßung", "", "Buongiorno, signora.", "Guten Tag, gnädige Frau."),
        w("it", "libro", "libro", "Buch", "/ˈli.bro/", "Substantiv", "maskulin", "Questo libro è bello.", "Dieses Buch ist schön."),
        w("it", "cane", "cane", "Hund", "/ˈka.ne/", "Substantiv", "maskulin", "Il cane corre nel parco.", "Der Hund läuft im Park."),
        w("it", "gatto", "gatto", "Katze", "/ˈɡat.to/", "Substantiv", "maskulin", "Il gatto dorme sul divano.", "Die Katze schläft auf dem Sofa."),
        w("it", "treno", "treno", "Zug", "/ˈtre.no/", "Substantiv", "maskulin", "Il treno parte alle otto.", "Der Zug fährt um acht ab."),
        w("it", "macchina", "macchina", "Auto", "/ˈmak.ki.na/", "Substantiv", "feminin", "La macchina è parcheggiata.", "Das Auto ist geparkt."),
        w("it", "soldi", "soldi", "Geld", "/ˈsɔl.di/", "Substantiv", "maskulin", "Non ho soldi con me.", "Ich habe kein Geld dabei."),
        w("it", "notte", "notte", "Nacht", "/ˈnɔt.te/", "Substantiv", "feminin", "Buona notte.", "Gute Nacht."),
        w("it", "mela", "mela", "Apfel", "/ˈme.la/", "Substantiv", "feminin", "Mangio una mela.", "Ich esse einen Apfel."),
        w("it", "latte", "latte", "Milch", "/ˈlat.te/", "Substantiv", "maskulin", "Un bicchiere di latte.", "Ein Glas Milch."),
        w("it", "porta", "porta", "Tür", "/ˈpɔr.ta/", "Substantiv", "feminin", "Chiudi la porta.", "Schließ die Tür."),
        w("it", "finestra", "finestra", "Fenster", "/fiˈnɛs.tra/", "Substantiv", "feminin", "Apri la finestra.", "Öffne das Fenster."),
        w("it", "tavolo", "tavolo", "Tisch", "/ˈta.vo.lo/", "Substantiv", "maskulin", "Metti i piatti sul tavolo.", "Stell die Teller auf den Tisch."),
        w("it", "mare", "mare", "Meer", "/ˈma.re/", "Substantiv", "maskulin", "Nuotiamo nel mare.", "Wir schwimmen im Meer."),
    )

    private fun en() = listOf(
        w("en", "water", "water", "Wasser", "/ˈwɔːtə/", "Substantiv", "", "The water is cold.", "Das Wasser ist kalt."),
        w("en", "bread", "bread", "Brot", "/bred/", "Substantiv", "", "I buy bread every morning.", "Ich kaufe jeden Morgen Brot."),
        w("en", "house", "house", "Haus", "/haʊs/", "Substantiv", "", "Our house is near the park.", "Unser Haus liegt nah am Park."),
        w("en", "time", "time", "Zeit", "/taɪm/", "Substantiv", "", "I don't have time today.", "Ich habe heute keine Zeit."),
        w("en", "day", "day", "Tag", "/deɪ/", "Substantiv", "", "Today is a good day.", "Heute ist ein guter Tag."),
        w("en", "year", "year", "Jahr", "/jɪə/", "Substantiv", "", "This year we travel to Scotland.", "Dieses Jahr reisen wir nach Schottland."),
        w("en", "woman", "woman", "Frau", "/ˈwʊmən/", "Substantiv", "", "The woman is reading a book.", "Die Frau liest ein Buch."),
        w("en", "man", "man", "Mann", "/mæn/", "Substantiv", "", "The man is waiting for the bus.", "Der Mann wartet auf den Bus."),
        w("en", "child", "child", "Kind", "/tʃaɪld/", "Substantiv", "", "The child is playing in the garden.", "Das Kind spielt im Garten."),
        w("en", "work", "work", "Arbeit", "/wɜːk/", "Substantiv", "", "I like my work.", "Ich mag meine Arbeit."),
        w("en", "school", "school", "Schule", "/skuːl/", "Substantiv", "", "The children go to school.", "Die Kinder gehen zur Schule."),
        w("en", "city", "city", "Stadt", "/ˈsɪti/", "Substantiv", "", "London is a huge city.", "London ist eine riesige Stadt."),
        w("en", "friend", "friend", "Freund", "/frend/", "Substantiv", "", "She is my best friend.", "Sie ist meine beste Freundin."),
        w("en", "family", "family", "Familie", "/ˈfæməli/", "Substantiv", "", "I have dinner with my family.", "Ich esse mit meiner Familie zu Abend."),
        w("en", "book", "book", "Buch", "/bʊk/", "Substantiv", "", "This book is interesting.", "Dieses Buch ist interessant."),
        w("en", "dog", "dog", "Hund", "/dɒɡ/", "Substantiv", "", "The dog runs in the park.", "Der Hund läuft im Park."),
        w("en", "cat", "cat", "Katze", "/kæt/", "Substantiv", "", "The cat sleeps on the sofa.", "Die Katze schläft auf dem Sofa."),
        w("en", "sun", "sun", "Sonne", "/sʌn/", "Substantiv", "", "The sun is shining.", "Die Sonne scheint."),
        w("en", "moon", "moon", "Mond", "/muːn/", "Substantiv", "", "The moon is full tonight.", "Der Mond ist heute Nacht voll."),
        w("en", "sea", "sea", "Meer", "/siː/", "Substantiv", "", "We swim in the sea.", "Wir schwimmen im Meer."),
        w("en", "street", "street", "Straße", "/striːt/", "Substantiv", "", "This street is very quiet.", "Diese Straße ist sehr ruhig."),
        w("en", "car", "car", "Auto", "/kɑː/", "Substantiv", "", "The car is parked outside.", "Das Auto ist draußen geparkt."),
        w("en", "train", "train", "Zug", "/treɪn/", "Substantiv", "", "The train leaves at eight.", "Der Zug fährt um acht ab."),
        w("en", "money", "money", "Geld", "/ˈmʌni/", "Substantiv", "", "I don't have much money on me.", "Ich habe nicht viel Geld dabei."),
        w("en", "question", "question", "Frage", "/ˈkwestʃən/", "Substantiv", "", "I have a question.", "Ich habe eine Frage."),
        w("en", "answer", "answer", "Antwort", "/ˈɑːnsə/", "Substantiv", "", "Her answer is clear.", "Ihre Antwort ist klar."),
        w("en", "night", "night", "Nacht", "/naɪt/", "Substantiv", "", "Good night.", "Gute Nacht."),
        w("en", "apple", "apple", "Apfel", "/ˈæpl/", "Substantiv", "", "I eat an apple every morning.", "Ich esse jeden Morgen einen Apfel."),
        w("en", "milk", "milk", "Milch", "/mɪlk/", "Substantiv", "", "A glass of milk, please.", "Ein Glas Milch, bitte."),
        w("en", "door", "door", "Tür", "/dɔː/", "Substantiv", "", "Please close the door.", "Bitte schließ die Tür."),
        w("en", "window", "window", "Fenster", "/ˈwɪndəʊ/", "Substantiv", "", "Please open the window.", "Bitte öffne das Fenster."),
        w("en", "table", "table", "Tisch", "/ˈteɪbl/", "Substantiv", "", "Put the plates on the table.", "Stell die Teller auf den Tisch."),
        w("en", "please", "please", "bitte", "/pliːz/", "Ausdruck", "", "A coffee, please.", "Einen Kaffee, bitte."),
        w("en", "thanks", "thank you", "Danke", "/θæŋk juː/", "Ausdruck", "", "Thank you for your help.", "Danke für deine Hilfe."),
        w("en", "hello", "hello", "Hallo", "/həˈləʊ/", "Begrüßung", "", "Hello, how are you?", "Hallo, wie geht's?"),
        w("en", "goodbye", "goodbye", "Auf Wiedersehen", "/ɡʊdˈbaɪ/", "Abschied", "", "Goodbye, see you tomorrow.", "Auf Wiedersehen, bis morgen."),
        w("en", "rain", "rain", "Regen", "/reɪn/", "Substantiv", "", "The rain stopped at noon.", "Der Regen hörte mittags auf."),
        w("en", "kitchen", "kitchen", "Küche", "/ˈkɪtʃɪn/", "Substantiv", "", "Dinner is ready in the kitchen.", "Das Abendessen ist in der Küche fertig."),
        w("en", "butterfly", "butterfly", "Schmetterling", "/ˈbʌtəflaɪ/", "Substantiv", "", "The butterfly lands on a flower.", "Der Schmetterling landet auf einer Blume."),
        w("en", "station", "station", "Bahnhof", "/ˈsteɪʃn/", "Substantiv", "", "The station is a ten-minute walk.", "Der Bahnhof ist zehn Minuten zu Fuß."),
    )
}
